### ISSUE TITLE
comments to howto

### ISSUE THREAD

**Issue by zumbruch** [Mrcl3/Compose-your-services#1]
@Mrcl3 
## DCS/docs/howto.rst

* "... after cloning" 
  * add clone command
* .env
  * can I comment out lines to keep old?
  * how do you envaluate this .env file? Last entry or first entry?
  * can you add some code 
          "cd directory; echo "LOC=$PWD" >> .env; echo "SUBSYSTEM=myCBM" >> .env"
* ./startup.sh CBM example
   * how do the arguments match the .env settings? Could you explain?
* 'depends on' sentence unclear for non compose users
...

**Comment by Mrcl3** [comment]
The changes addressing those issues has been implemented by changing from shell to python.
